name = "waalge/mre-fuzz-fail"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'waalge/mre-fuzz-fail'"

[repository]
user = "waalge"
project = "mre-fuzz-fail"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"
